import 'package:equatable/equatable.dart';

import 'exemplar_item.dart';

/// Represents a style or rhetorical move warning generated by the checker.
class WarningItem extends Equatable {
  final String id;
  final String severity;
  final String section;
  final String title;
  final String message;
  final ExemplarItem? exemplar;

  const WarningItem({
    required this.id,
    required this.severity,
    required this.section,
    required this.title,
    required this.message,
    this.exemplar,
  });

  bool get isGapWarning =>
      id == 'W-GAP-01' ||
      title.toLowerCase().contains('research gap') ||
      message.toLowerCase().contains('research gap');

  bool get isRhetoricalMoveWarning =>
      id == 'W-MOVE-01' ||
      isGapWarning ||
      title.toLowerCase().contains('missing');

  bool get isSentenceLengthWarning =>
      id == 'W-STYLE-01' ||
      title.toLowerCase().contains('sentence length');

  bool get isVoicePersonWarning =>
      id == 'W-STYLE-02' ||
      title.toLowerCase().contains('passive') ||
      title.toLowerCase().contains('person');

  bool get isStanceWarning =>
      id == 'W-STYLE-03' ||
      title.toLowerCase().contains('hedge') ||
      title.toLowerCase().contains('booster');

  factory WarningItem.fromMap(Map<String, dynamic> map) {
    return WarningItem(
      id: map['id'] as String? ?? '',
      severity: (map['severity'] as String? ?? 'MEDIUM').toUpperCase(),
      section: map['section'] as String? ?? '',
      title: map['title'] as String? ?? '',
      message: map['message'] as String? ?? '',
      exemplar: map['exemplar'] != null && map['exemplar'] is Map<String, dynamic>
          ? ExemplarItem.fromMap(map['exemplar'] as Map<String, dynamic>)
          : null,
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'severity': severity,
      'section': section,
      'title': title,
      'message': message,
      'exemplar': exemplar?.toMap(),
    };
  }

  @override
  List<Object?> get props => [id, severity, section, title, message, exemplar];
}
